[package]
name = "rust-web-starter"
version = "0.1.0"
authors = ["wmzy"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0.0"
listenfd = "0.3.3"
actix-rt = "1.0.0"
serde = "1.0.104"
